### PR TITLE
Add provider for linux_aarch64

### PR DESCRIPTION
**Pull request by Zandew**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zandew** [comment]
@conda-forge-admin, please rerender

**Comment by micknudsen** [comment]
I have no experience with C, so I have no clue what these changes mean. Why are they needed? I am not really sure, how I became code owner on this recipe 🤔

**Comment by Zandew** [comment]
Not sure if there's actually any C code (I definitely didn't write any, maybe in the built files?), but the first commit adds a provider that allows pomegranate to be built for the `linux_aarch64` platform.

**Comment by micknudsen** [comment]
Oh, now I see. All the stuff, I was looking at, seems to have been auto-generated by the conda-forge bot.

**Review by micknudsen — APPROVED** [review]

**Comment by micknudsen** [comment]
@conda-forge-admin Please merge

**Pull request merged**
